using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerProjects
{
    class _2nd
    {

        /*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
         * By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/



        int res = Fibonacci();

        static int Fibonacci()
        {
            int sum = 0;
            int num1 = 1;
            int num2 = 2;

            while (num1 <= 4000000)
            {
                int num1temp = num1;
                num1 = num2;
                num2 += num1temp;

                if ((num1 % 2) == 0)
                {
                    sum += num1;
                }
            }
            return sum; //returns 4613732
        }
     
    }
}
